name: myresumeapp
description: This is the mobile version of my resume app.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter 

  # UI Components
  cupertino_icons: ^1.0.5
  animations: ^2.0.7
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_sticky_header: ^ 0.6.4
  font_awesome_flutter: ^ 10.2.1

  # Utilities
  url_launcher: ^6.1.6
  page_transition: ^2.0.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
